make     cli GEN_TRANS_TYPE=i2cmb_test
make run_cli GEN_TRANS_TYPE=test_i2cmb_reg_addrs TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmb_reg_defaults TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmb_reg_faultaddrs TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmb_reg_transactions TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmb_reg_writeouts TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmbFSM_before TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmbFSM_starts TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmbFSM_stops TEST_SEED=random
make run_cli GEN_TRANS_TYPE=test_i2cmbFSM_writefirst TEST_SEED=random
make merge_coverage
