#!/bin/sh

cd /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project
run_times=0
until [ $run_times -gt 1 ]
do
    ((run_times++))
    if [ $run_times -gt 1 ]
    then
        export SNPS_PW_SIM_SERVER_RERUN=1
        script_pgid=`ps -o pgid= $$ | grep -o '[0-9]*'`
        pid_with_same_pgid=`ps -eo pid,pgid | awk '$2 == "'$script_pgid'" { print $1 }'`
        echo $pid_with_same_pgid | grep -v $$ | xargs kill -9
    fi
    primewave -gui 0 -uniqueString 424077b79e1069eec9c0fa9fcb9fea2f9b5804bf5a3160b21ca54e530ed02967e332389e68257413a0c31fca7d4a06dd -python 0 -command "source /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/synopsys_custom/sim_server/custom_compiler.svkolach/stb.group8.static_row_decoder_3by8.schematic.session2/sim_server_init.tcl" -log /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/synopsys_custom/primewave_session2_sim_server_job1 -libDefFile /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/lib.defs && break
done
