#!/bin/sh

cd /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project
run_times=0
until [ $run_times -gt 1 ]
do
    ((run_times++))
    if [ $run_times -gt 1 ]
    then
        export SNPS_PW_SIM_SERVER_RERUN=1
        script_pgid=`ps -o pgid= $$ | grep -o '[0-9]*'`
        pid_with_same_pgid=`ps -eo pid,pgid | awk '$2 == "'$script_pgid'" { print $1 }'`
        echo $pid_with_same_pgid | grep -v $$ | xargs kill -9
    fi
    primewave -gui 0 -uniqueString 424077b79e1069eedd8578c011d9500f2c97bf2f98d5b5cdf93a5ef511cc936ba8013c6c0fcd55d645d960f1d3bee243 -python 0 -command "source /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/synopsys_custom/sim_server/custom_compiler.nbandeh/stb.group8.2to4decodermux_tb.schematic.session0/sim_server_init.tcl" -log /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/synopsys_custom/primewave_session0_sim_server_job1 -libDefFile /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/lib.defs && break
done
