// Monitor is the observer: it passively watches the DUT interface signals and reports what it
// sees
`ifndef WRITE_FIFO_MONITOR__SV
`define WRITE_FIFO_MONITOR__SV
class write_fifo_monitor extends uvm_monitor;

    virtual wr_if wr_if_h;
    // Connects the monitor to the DUT's wr_if interface
    // To see what the DUT is doing (same one as the driver uses)

    uvm_analysis_port #(my_transaction) ap_h;
    // To send observed transactions to other components
    // Anything connected to this port will receive monitored data
    // It acts as a "broadcast channel" for transactions

    `uvm_component_utils(write_fifo_monitor)

    function new(string name = "write_fifo_monitor", uvm_component parent = null);
        super.new(name, parent);
    endfunction

    // Retrieves the virtual interface that was set in testbench.sv
    // Stops the simulation if not found
    // Instantiates the analysis port
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        if(!uvm_config_db#(virtual wr_if)::get(this, "", "wr_if", wr_if_h))
            `uvm_fatal("write_fifo_monitor", "virtual interface must be set for wr_if!!!")
        ap_h = new("ap_h", this);
    endfunction

    extern task main_phase(uvm_phase phase);
    extern task collect_one_pkt(my_transaction tr_h);

endclass

task write_fifo_monitor::main_phase(uvm_phase phase);
    my_transaction tr_h;
    while(1) begin
        // 1. Create a new transaction
        // 2. Calls collect_one_pkt(tr) to sample data from the DUT interface
        // 3. Sends ap.write() to whoever is listening(usually the scoreboard)
        tr_h = new("tr_h");
        collect_one_pkt(tr_h);
        ap_h.write(tr_h);
    end
endtask

task write_fifo_monitor::collect_one_pkt(my_transaction tr_h);
    // 1. Wait for a positive clock edge
    // 2. Check if write enable (winc) is asserted
    //      - if not, keep waiting
    //      - When winc = 1, means write operation is happening
    // 3. Capture the data: whatever is being written into the FIFO at that moment
    while(1) begin
        @(posedge wr_if_h.wclk);
        if(wr_if_h.winc) break;
    end
    `uvm_info("write_fifo_monitor", "begin to collect one pkt", UVM_MEDIUM);
    tr_h.data = wr_if_h.wdata;
    `uvm_info("write_fifo_monitor", "end collect one pkt", UVM_MEDIUM);
endtask

// Expected data: Generated by the sequence and sent to the driver
// Observed data: Captured by the monitor from the DUT signals
`endif
