#!/bin/sh

cd /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project
run_times=0
until [ $run_times -gt 1 ]
do
    ((run_times++))
    if [ $run_times -gt 1 ]
    then
        export SNPS_PW_SIM_SERVER_RERUN=1
        script_pgid=`ps -o pgid= $$ | grep -o '[0-9]*'`
        pid_with_same_pgid=`ps -eo pid,pgid | awk '$2 == "'$script_pgid'" { print $1 }'`
        echo $pid_with_same_pgid | grep -v $$ | xargs kill -9
    fi
    primewave -gui 0 -uniqueString 424077b79e1069ee777771a163345433abe641e08b843adf103ebf0b7deb01df4d53f467da0e3edf -python 0 -command "source /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/synopsys_custom/sim_server/custom_compiler.svkolach/stb.group8.tb2025_1.schematic.session2/sim_server_init.tcl" -log /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/synopsys_custom/primewave_session2_sim_server_job1 -libDefFile /mnt/coe/workspace/ece/ece546-spr25/group8/group8_project/lib.defs && break
done
