// ------------------------------------------------------------
// RISC-V Core Top
// ------------------------------------------------------------
// Simple RV32I core with a single-stage datapath:
//
//   • PC generation
//   • Instruction fetch
//   • Decode
//   • Register file read
//   • Execute (ALU + branch decision)
//   • Data memory access
//   • Register write-back
//
// No pipeline registers are used here; everything happens in
// one cycle after instruction fetch (combinational datapath).
// ------------------------------------------------------------

module riscv_core_top
  import riscv_core_pkg::*;
#(
  parameter logic [31:0] RESET_PC = 32'h0000_1000   // Initial PC value
)(
    input  logic         clk_i,
    input  logic         reset_ni,

    // --------------------------------------------------------
    // Instruction memory interface
    // --------------------------------------------------------
    output logic         instr_mem_req_o,
    output logic [31:0]  instr_mem_addr_o,
    input  logic [31:0]  instr_mem_rd_data_i,

    // --------------------------------------------------------
    // Data memory interface
    // --------------------------------------------------------
    output logic         data_mem_req_o,
    output logic [31:0]  data_mem_addr_o,
    output logic [1:0]   data_mem_byte_en_o,
    output logic         data_mem_wr_o,
    output logic [31:0]  data_mem_wr_data_o,
    input  logic [31:0]  data_mem_rd_data_i
);

  // ==========================================================
  // Internal signals
  // ==========================================================

  // PC and next-PC signals
  logic [31:0] pc_q;             // Current PC
  logic [31:0] nxt_seq_pc;       // PC + 4
  logic [31:0] nxt_pc;           // Next PC after branch/jump logic
  logic        reset_seen_q;     // Becomes 1 after first cycle out of reset

  // Instruction fetch / decode signals
  logic [31:0] instr_if;         // Instruction from fetch to decode

  logic [4:0]  dec_rs1_addr;
  logic [4:0]  dec_rs2_addr;
  logic [4:0]  dec_rd_addr;

  logic [6:0]  dec_opcode;
  logic [2:0]  dec_funct3;
  logic [6:0]  dec_funct7;

  logic        dec_is_r_type;
  logic        dec_is_i_type;
  logic        dec_is_s_type;
  logic        dec_is_b_type;
  logic        dec_is_u_type;
  logic        dec_is_j_type;

  logic [31:0] dec_imm;          // Immediate generated by decode stage

  // Register file signals
  logic [31:0] rf_rs1_data;
  logic [31:0] rf_rs2_data;
  logic [31:0] rf_wr_data;

  // Control unit signals
  logic            ctl_pc_sel;
  logic            ctl_op1_sel;
  logic            ctl_op2_sel;
  alu_op_t         ctl_alu_op;
  rf_wdata_src_t   ctl_rf_wdata_sel;
  logic            ctl_data_req;
  mem_access_size_t ctl_data_byte;
  logic            ctl_data_wr;
  logic            ctl_zero_extend;
  logic            ctl_rf_wr_en;

  // Execute / branch signals
  logic [31:0] alu_opr_a;
  logic [31:0] alu_opr_b;
  logic [31:0] alu_result;
  logic        branch_taken;

  // Data memory read data (after extension)
  logic [31:0] data_mem_rd_data_core;


`ifdef YARP_VAL
  // Optional debug view of register file
  logic [31:0][31:0] regfile_view;
`endif

  // ==========================================================
  // Reset seen flag
  // ==========================================================
  // We only start updating PC after we've seen at least one
  // rising edge with reset deasserted.
  // ==========================================================
  always_ff @(posedge clk_i or negedge reset_ni) begin
    if (!reset_ni)
      reset_seen_q <= 1'b0;
    else
      reset_seen_q <= 1'b1;
  end

  // ==========================================================
  // Program Counter Logic
  // ==========================================================
  // nxt_seq_pc: PC + 4
  // nxt_pc:
  //   - If branch_taken or a jump (ctl_pc_sel) is asserted:
  //       use ALU result as next PC (aligned to 2 bytes)
  //   - Else:
  //       PC + 4
  //
  // The low bit is forced to 0 for alignment:
  //   {alu_result[31:1], 1'b0}
  // ==========================================================
  assign nxt_seq_pc = pc_q + 32'h4;

  assign nxt_pc =
      (branch_taken || ctl_pc_sel) ? {alu_result[31:1], 1'b0} :
                                     nxt_seq_pc;

  always_ff @(posedge clk_i or negedge reset_ni) begin
    if (!reset_ni)
      pc_q <= RESET_PC;
    else if (reset_seen_q)
      pc_q <= nxt_pc;
  end

  // ==========================================================
  // Instruction Fetch Stage
  // ==========================================================
  instr_fetch_stage u_instr_fetch_stage (
    .clk_i        (clk_i),
    .reset_ni     (reset_ni),
    .pc_i         (pc_q),

    .imem_req_o   (instr_mem_req_o),
    .imem_addr_o  (instr_mem_addr_o),
    .imem_data_i  (instr_mem_rd_data_i),

    .instr_o      (instr_if)
  );

  // ==========================================================
  // Decode Stage
  // ==========================================================
  decode_stage u_decode_stage (
    .instr_i          (instr_if),

    .rs1_o            (dec_rs1_addr),
    .rs2_o            (dec_rs2_addr),
    .rd_o             (dec_rd_addr),

    .opcode_o         (dec_opcode),
    .funct3_o         (dec_funct3),
    .funct7_o         (dec_funct7),

    .is_r_type_o      (dec_is_r_type),
    .is_i_type_o      (dec_is_i_type),
    .is_s_type_o      (dec_is_s_type),
    .is_b_type_o      (dec_is_b_type),
    .is_u_type_o      (dec_is_u_type),
    .is_j_type_o      (dec_is_j_type),

    .imm_o            (dec_imm)
  );

  // ==========================================================
  // Register File
  // ==========================================================
  // rf_wr_data is selected in WB-like logic:
  //   • RF_WDATA_ALU : ALU result
  //   • RF_WDATA_MEM : data from memory
  //   • RF_WDATA_IMM : immediate (for LUI)
  //   • RF_WDATA_PC  : PC+4 (for JAL/JALR)
  // ==========================================================
  always_comb begin
    unique case (ctl_rf_wdata_sel)
      RF_WDATA_ALU: rf_wr_data = alu_result;
      RF_WDATA_MEM: rf_wr_data = data_mem_rd_data_core;
      RF_WDATA_IMM: rf_wr_data = dec_imm;
      RF_WDATA_PC : rf_wr_data = nxt_seq_pc;
      default     : rf_wr_data = 32'h0000_0000;
    endcase
  end

  riscv_regfile u_riscv_regfile (
    .clk_i        (clk_i),
    .reset_ni     (reset_ni),

    .rs1_addr_i   (dec_rs1_addr),
    .rs2_addr_i   (dec_rs2_addr),

    .rd_addr_i    (dec_rd_addr),
    .rd_wr_en_i   (ctl_rf_wr_en),
    .rd_wr_data_i (rf_wr_data),

    .rs1_data_o   (rf_rs1_data),
    .rs2_data_o   (rf_rs2_data)
  );

`ifdef YARP_VAL
  // Optional binding for waveform inspection of regfile
  assign regfile_view = u_riscv_regfile.regfile_q;
`endif

  // ==========================================================
  // Control Unit
  // ==========================================================
  control_unit u_control_unit (
    .is_r_type_i         (dec_is_r_type),
    .is_i_type_i         (dec_is_i_type),
    .is_s_type_i         (dec_is_s_type),
    .is_b_type_i         (dec_is_b_type),
    .is_u_type_i         (dec_is_u_type),
    .is_j_type_i         (dec_is_j_type),

    .instr_funct3_i      (dec_funct3),
    .instr_funct7_bit5_i (dec_funct7[5]),
    .instr_opcode_i      (dec_opcode),

    .pc_sel_o            (ctl_pc_sel),
    .op1_sel_o           (ctl_op1_sel),
    .op2_sel_o           (ctl_op2_sel),
    .alu_op_o            (ctl_alu_op),
    .rf_wdata_src_o      (ctl_rf_wdata_sel),
    .data_req_o          (ctl_data_req),
    .data_byte_o         (ctl_data_byte),
    .data_wr_o           (ctl_data_wr),
    .zero_extend_o       (ctl_zero_extend),
    .rf_wr_en_o          (ctl_rf_wr_en)
  );

  // ==========================================================
  // Branch Control
  // ==========================================================
  branch_control_unit u_branch_control_unit (
    .opr_a_i        (rf_rs1_data),
    .opr_b_i        (rf_rs2_data),
    .is_b_type_i    (dec_is_b_type),
    .instr_funct3_i (dec_funct3),
    .branch_taken_o (branch_taken)
  );

  // ==========================================================
  // Execute Unit (ALU)
  // ==========================================================
  // Operand selection:
  //   op1_sel:
  //     0 -> RS1
  //     1 -> PC
  //   op2_sel:
  //     0 -> RS2
  //     1 -> Immediate
  // ==========================================================
  assign alu_opr_a = ctl_op1_sel ? pc_q      : rf_rs1_data;
  assign alu_opr_b = ctl_op2_sel ? dec_imm   : rf_rs2_data;

  execute_stage u_execute_stage (
    .opr_a_i        (alu_opr_a),
    .opr_b_i        (alu_opr_b),
    .alu_op_i       (ctl_alu_op),
    .alu_result_o   (alu_result)
  );

  // ==========================================================
  // Data Memory Stage
  // ==========================================================
  data_memory_stage u_data_memory_stage (
    .clk_i              (clk_i),
    .reset_ni           (reset_ni),

    .data_req_i         (ctl_data_req),
    .data_addr_i        (alu_result),
    .data_byte_en_i     (ctl_data_byte),
    .data_wr_i          (ctl_data_wr),
    .data_wr_data_i     (rf_rs2_data),
    .data_zero_extend_i (ctl_zero_extend),

    .data_mem_req_o     (data_mem_req_o),
    .data_mem_addr_o    (data_mem_addr_o),
    .data_mem_byte_en_o (data_mem_byte_en_o),
    .data_mem_wr_o      (data_mem_wr_o),
    .data_mem_wr_data_o (data_mem_wr_data_o),

    .mem_rd_data_i      (data_mem_rd_data_i),
    .data_rd_data_o     (data_mem_rd_data_core)
  );

endmodule
